### ISSUE TITLE
Problem: The program cannot be exited

### ISSUE THREAD

**Issue by zhangtian1993** [smilecc/node-redisson#3]
Very nice project, thanks for your efforts. But I encountered a problem in use, The program cannot be exited.

The following is an example:
```
import {Redisson} from 'node-redisson';

const redisson = new Redisson({
    redis: {
        options: {
            host: 'localhost',
            password: '123456',
        },
    },
});

async function test() {
    const lock = redisson.getLock('Example:LockName');
    await lock.lock();
    await lock.unlock();
}

await test();

await redisson.redis.quit();
console.info('done');
```
In the example, 'done' is output, but the program does not exit.

**Comment by smilecc** [comment]
Thanks for your feedback, I will check it.

**Comment by smilecc** [comment]
The reason for this problem is that `NodeRedisson` will also hold another Redis connection for subscription.

I adds a `quit()` method for `Redisson` in v1.0.3 , so you can do this:

```ts
// quit the redisson client
await redisson.quit();
```
